version: '3.7'
services:
    psql:
        container_name: tripsit_db
        restart: unless-stopped
        image: postgres:14.5-alpine
        ports:
            - 5432:5432
        networks:
            - backend
        # network_mode: host
        volumes:
            - http_api_psql_data:/var/lib/postgresql/data
            - ./initialize-database.sh:/docker-entrypoint-initdb.d/initialize-database.sh
        env_file:
            - .env

    mailhog:
        container_name: tripsit_smtp
        restart: unless-stopped
        image: cd2team/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - backend

networks: 
  backend:
    driver: bridge
    name: tripbot_backend

volumes:
    http_api_psql_data:
