version: '3.7'

services:

    psql:
        container_name: tripsit_db
        image: postgres:14.5-alpine
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - http_api_psql_data:/var/lib/postgresql/data
            - ./initialize-database.sh:/docker-entrypoint-initdb.d/initialize-database.sh

    mailhog:
        container_name: tripsit_smtp
        image: cd2team/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025

volumes:
    http_api_psql_data:
