name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to athena.tripsit.me
      uses: appleboy/ssh-action@master
      with:
        host: dev.tripsit.me
        username: http-api
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/http-api/http-api
          git checkout .
          git pull
          npm ci
          npm run deploy
