name: deploy
run-name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to athena.tripsit.me
      uses: appleboy/ssh-action@master
      with:
        host: athena.tripsit.me
        username: http-api
        script: |
          cd /home/http-api/http-api
          git checkout .
          git pull
          npm ci
          npm run migration
          pm2 restart tripsit-http-api
