name: test

on:
  pull_request:
    branches:
      - master
      - development
      - feature/discord-api

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: cp .env.example .env
      - run: cp config.example.json config.json
      - run: docker-compose up -d
      - run: npm t
