
name: test
run-name: Automated Tests

on:
  pull_request:
    branches:
      - master
      - development
      - feature/discord-api

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install Node packages
        run: npm ci
      - name: Copy env file
        run: cp .env.example .env
      - name: Copy config file
        run: cp config.example.json config.json
      - name: Docker compose
        run: docker-compose up -d
      - name: Idk some kind of test
        run: npm t
